"use client";
import { ThemeProvider } from "@emotion/react";
import "./globals.css";
import type { Metadata } from "next";
import theme from "../../theme";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <ThemeProvider theme={theme}> {children}</ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
